title: Thomas Barker
description: A final year Computer Science Student at the University of Cambridge.
social_link: twitter
social_username: broccolini
github_repo: athena
github_username: tbarker2001
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /zealous_toejam
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
